BusTracking.Web/Areas/Admin/Controllers/LineController.cs
using BusTracking.Data.Models;
using BusTracking.Infrastructure.Services.LineService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using System.Text.Json;
using BusTracking.Core.ViewModels;
using BusTracking.Core.Dtos.LineDtos;
using BusTracking.Core.ViewModels.LinesViewModels;
using BusTracking.Infrastructure.Services.UserService;
using BusTracking.Core.Enums;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BusTracking.Web.Areas.Admin.Controllers
{
    public class LineController : BaseController
    {

        private readonly ILineService _line;

        public LineController(IUserService user, ILineService line) : base(user)
        {
            _line = line;
        }

        // GET: LineController
        public async Task<ActionResult> Index()
        {
            if (userType != UserType.Administrator.ToString() && userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (userType != UserType.Administrator.ToString() && companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }

            var compositeVM = new LineCompositeViewModel
            {
                ListLines = await _line.GetAll(CompanyId)
            };
            return View(compositeVM);
        }

        // GET: LineController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (userType != UserType.Administrator.ToString() && userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (userType != UserType.Administrator.ToString() && companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }

            var line = await _line.Get(id);

            if (line == null)
            {
                return Redirect("/Admin/Base/NotFound");
            }
            else if (userType != UserType.Administrator.ToString() && line.CompanyId != CompanyId)
            {
                return Redirect("/Admin/Base/Unauthorized");
            }


            var compositeVM = new LineCompositeViewModel
            {
                Line = line
            };

            return View(compositeVM);
        }

        // POST: LineController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLineDto createLineDto)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }
            try
            {
                if (ModelState.IsValid)
                {
                    var line = await _line.Create(createLineDto);
                    return Redirect("~/Admin/Company/Details/" + createLineDto.CompanyId);
                    //return Ok(OperationResuslts.AddSuccessResult());
                }
                return Redirect("~/Admin/Company/Details/" + createLineDto.CompanyId);
            }
            catch
            {
                return Redirect("~/Admin/Company/Details/" + createLineDto.CompanyId);
            }
        }


        // POST: LineController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UpdateLineDto updateDto)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }
            try
            {
                if (ModelState.IsValid)
                {
                    var line = await _line.Update(updateDto);
                    return Redirect("~/Admin/Line/Details/" + line);
                }
                return Redirect("~/Admin/Line/Details/" + updateDto.Id);
            }
            catch
            {
                return Redirect("~/Admin/Line/Details/" + updateDto.Id);
            }
        }

        // POST: LineController/Edit/5
        [HttpGet]
        public async Task<ActionResult> GenerateCode(int id)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }
            try
            {
                await _line.GenerateNewCode(id);
                return Redirect("~/Admin/Line/Details/" + id);
            }
            catch
            {
                return Redirect("~/Admin/Line/Details/" + id);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            else if (companyStatus != Status.Activated.ToString())
            {
                return Redirect("/Admin/Company/Pending");
            }
            try
            {
                await _line.Delete(id);
                string referer = Request.Headers["Referer"].ToString();
                return Redirect(referer);
            }
            catch (Exception)
            {
                return Redirect("/Admin/Base/NotFound");
            }

        }
    }
}

BusTracking.Web/Areas/Admin/Controllers/LineStopPointController.cs
using BusTracking.Core.Dtos.LineStopPointDtos;
using BusTracking.Core.Enums;
using BusTracking.Data.Models;
using BusTracking.Infrastructure.Services.BusService;
using BusTracking.Infrastructure.Services.CompanyService;
using BusTracking.Infrastructure.Services.LineService;
using BusTracking.Infrastructure.Services.LineStopPointService;
using BusTracking.Infrastructure.Services.UserService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Tavis.UriTemplates;

namespace BusTracking.Web.Areas.Admin.Controllers
{
    public class LineStopPointController : BaseController
    {
        private readonly ILineStopPointService _lineStopPoint;
        private readonly ILineService _line;

        public LineStopPointController(IUserService user,
            ILineStopPointService lineStopPoint,
            ILineService line) : base(user)
        {
            _lineStopPoint = lineStopPoint;
            _line = line;
        }

        // GET: LineStopPointController/Details/5
        public async Task<ActionResult> Details(int lineId)
        {
            try
            {
                ViewBag.lineId = lineId;
                var result = await _lineStopPoint.GetAllByLineId(lineId);
                return View(result);
            }
            catch (Exception)
            {
                return RedirectToAction("NotFound", "Base");
                throw;
            }
        }

        // GET: LineStopPointController/Create
        public async Task<ActionResult> Create(int lineId)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            var line = await _line.Get(lineId);

            if (line == null)
            {
                return Redirect("/Admin/Base/NotFound");
            }
            else if (userType != UserType.Administrator.ToString() && line.CompanyId != CompanyId)
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            try
            {
                ViewBag.lineId = lineId;
                var result = await _lineStopPoint.GetAllByLineId(lineId);
                return View(result);
            }
            catch (Exception)
            {
                return Redirect("/Admin/Base/NotFound");
                throw;
            }

        }

        // POST: LineStopPointController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLineStopPointDto createDto)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            var line = await _line.Get(createDto.LineId);

            if (line == null)
            {
                return Redirect("/Admin/Base/NotFound");
            }
            else if (userType != UserType.Administrator.ToString() && line.CompanyId != CompanyId)
            {
                return Redirect("/Admin/Base/Unauthorized");
            }

            string referer = Request.Headers["Referer"].ToString();

            try
            {
                if (ModelState.IsValid)
                {
                    var lineStopPoint = await _lineStopPoint.Create(createDto);
                    return Redirect(referer);
                    //return Ok(OperationResults.AddSuccessResult());
                }
                return Redirect(referer);
            }
            catch
            {
                return Redirect(referer);
            }
        }


        // GET: LineStopPointController/Get
        public async Task<ActionResult> Get(int lineId)
        {
            try
            {
                var result = await _lineStopPoint.GetAllByLineId(lineId);
                return Json(result);
            }
            catch (Exception ex)
            {
                // Example: Returning a custom error message
                return StatusCode(500, "An error occurred while retrieving line stop points. Please try again later.");
            }
        }

        // GET: LineStopPointController/Edit/5
        public ActionResult Edit(int id , int order)
        {
            ViewBag.Id = id;
            ViewBag.Order = order;
            return View();
        }

        // POST: LineStopPointController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (userType != UserType.CompanyAdmin.ToString())
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            var lineStopPoint = await _lineStopPoint.Get(id);
            if (lineStopPoint == null)
            {
                return Redirect("/Admin/Base/NotFound");
            }

            var line = await _line.Get(lineStopPoint.LineId);

            if (line == null)
            {
                return Redirect("/Admin/Base/NotFound");
            }
            else if (userType != UserType.Administrator.ToString() && line.CompanyId != CompanyId)
            {
                return Redirect("/Admin/Base/Unauthorized");
            }
            try
            {
                await _lineStopPoint.Delete(id);


                string referer = Request.Headers["Referer"].ToString();
                return Redirect(referer);
            }
            catch (Exception)
            {
                return Redirect("/Admin/Base/NotFound");
            }
        }
    }
}

BusTracking.Web/Areas/Admin/Views/Line/Details.cshtml
@model LineCompositeViewModel;

@{
    ViewData["Title"] = "company Details";
}

@section Css{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYSc1HVpre2VsOCttajANlEwB3-Vzb7N8"></script>

    <script>
        function initMap() {

            var locations = [


        @foreach (var point in Model.Line.LinesSP)
        {

            @:['<h4>' + '@point.StopPoint.Name' + '</h4>', @point.StopPoint.Latitude, @point.StopPoint.Longitude],

        }


                                                                                                                                          ];

            var map = new google.maps.Map(document.getElementById('map'), {
        @if (Model.Line.Bus != null)
        {
            @:center: { lat: @Model.Line.Bus.Latitude, lng: @Model.Line.Bus.Longitude },
        }
        else
        {
            @:center: { lat: 31.279393272965454, lng: 34.25513974267617 },
        }
                zoom: 15,
                styles: [
                {
                    featureType: 'poi',
                    elementType: 'labels',
                    stylers: [{ visibility: 'off' }]
                }
            ]
                    });
        var infowindow = new google.maps.InfoWindow();
        var busStopIcon = {
            url: '/AdminSection/img/BusStopPointNonAccess.png',
            size: new google.maps.Size(35, 35),
            scaledSize: new google.maps.Size(35, 35)
        };
        var marker, i;
        for (i = 0; i < locations.length; i++) {
            marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                map: map,
                title: locations[i][0],
                icon: busStopIcon
            });

            google.maps.event.addListener(marker, 'click', (function (marker, i) {
                return function () {
                    infowindow.setContent(locations[i][0]);
                    infowindow.open(map, marker);
                }
            })(marker, i));
        }

        @if (Model.Line.Bus != null)
        {
            @:    var busMarker = new google.maps.Marker({
            @:position: new google.maps.LatLng(@Model.Line.Bus.Latitude, @Model.Line.Bus.Longitude),
            @:map: map,
            @:icon:
            @:{
            @:url: '/AdminSection/img/bus-icon.png',
            @:size: new google.maps.Size(32, 32),
            @:scaledSize: new google.maps.Size(32, 32)
            @:  }
            @:  });

            @:    function getLiveBusLocation()
            @:{
            @:$.ajax({
            @:url: '/Admin/Bus/GetBusLocation/@Model.Line.Bus.Id',
            @:type: 'GET',
            @:success: function (data) {
            @:              if (busMarker)
            @:{
            @:busMarker.setPosition(new google.maps.LatLng(data.latitude, data.longitude));
            @:console.log(data.latitude);
            @:console.log(data.longitude);
            @:          }
            @:      },
            @:error: function () {
            @:console.log('Error fetching bus location');
            @:       }
            @:   });
            @:    }

            @:busMarker.addListener('click', function () {
            @:window.open('/Admin/Bus/Details/@Model.Line.Bus.Id', '_blank');
            @: });
            @:setInterval(getLiveBusLocation, 5000);

        }


                                }

    </script>

    <style>
        #map {
            height: 800px;
            width: 100%;
        }
    </style>
}
@section Scripts{
    <script src="~/AdminSection/vendor/bootstrap-datepicker.js"></script>
    <script>$('input.date-pick').datepicker();</script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYSc1HVpre2VsOCttajANlEwB3-Vzb7N8&callback=initMap"></script>
}
<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="~/Admin">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Line</li>
    </ol>
    <div class="box_general pb-3">
        <div class="header_box">
            <h2 class="d-inline-block">Line Details</h2>
        </div>
        <div class="list_general order">
            <ul>
                <li>
                    <figure><img src="img/item_1.jpg" alt=""></figure>
                    <h4>
                        @Model.Line.Name
                        @if (Model.Line.Bus != null)
                        {
                            <i class="approved">Active</i>
                        }
                        else
                        {

                            <i class="cancel">Inactive</i>

                        }


                    </h4>
                    <ul class="booking_list">
                        <li>
                            <strong>Code : </strong>
                            @if (@ViewBag.UserType == UserType.CompanyAdmin.ToString())
                            {
                                @Model.Line.Code
                            }
                            else
                            {
                                @: **********
                            }
                        </li>
                        <li>
                            <strong>Company : </strong>
                            <a href="~/Admin/Company/Details/@Model.Line.Company.Id">  @Model.Line.Company.Name</a>
                        </li>
                        <li>
                            <strong>Expired : </strong>
                            <i class="@(Model.Line.ActiveExpired > DateTime.Now ? "approved" : "cancel")">
                                @Model.Line.ActiveExpired
                            </i>
                        </li>
                        <li><strong>Bus : </strong>@(Model.Line.Bus != null ? @Model.Line.Bus.Name : "Null") </li>
                        @if (@ViewBag.UserType == UserType.CompanyAdmin.ToString())
                        {
                            <p>
                                <a href="#0" class="btn_1" data-toggle="modal" data-target="#client_detail_modal"><i class="fa fa-fw fa-pencil"></i> Edit Line detail</a>
                                <a href="~/Admin/Line/GenerateCode/@Model.Line.Id" class="btn_1"><i class="fa fa-fw fa-pencil"></i>Generate New Code</a>
                                <a asp-area="Admin" asp-action="Create" asp-controller="LineStopPoint"
                               asp-route-lineId="@Model.Line.Id" class="btn_1"><i class="fa fa-fw fa-pencil"></i> Edit Itinerary </a>
                            </p>
                        }
                    </ul>

                </li>
            </ul>
        </div>
        <hr>
        <h5>The stopping points that this line passes through :</h5>
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Order</th>
                        <th>Name</th>
                        <th>City</th>
                        <th>Address</th>
                        <th>TimeAccess</th>
                        <th>IsAccess</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Order</th>
                        <th>Name</th>
                        <th>City</th>
                        <th>Address</th>
                        <th>TimeAccess</th>
                        <th>IsAccess</th>
                    </tr>
                </tfoot>
                <tbody>
                    @if (Model.Line.LinesSP.Any())
                    {
                        foreach (var point in Model.Line.LinesSP)
                        {
                            <tr>
                                <td>@point.Order </td>
                                <td>@point.StopPoint.Name</td>
                                <td>@point.StopPoint.City.Name</td>
                                <td>@point.StopPoint.Address</td>
                                <td>@point.TimeAccess</td>
                                <td>@point.IsAccess</td>
                            </tr>
                        }

                    }


                </tbody>
            </table>
        </div>



        <div class="table-responsive">
            <!--Map-->
            <div id="map"></div>
        </div>

    </div>
</div>




<!-- Line Detail Modal -->
<form action="~/Admin/Line/Edit" method="post" enctype="multipart/form-data">
    <div class="modal fade" id="client_detail_modal" tabindex="-1" role="dialog" aria-labelledby="client_detail_modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="client_detail_modalLabel">Edit Line detail</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input hidden required asp-for="UpdateDto.Id" value="@Model.Line.Id">
                    <div class="form-group">
                        <label>Name</label>
                        <input required asp-for="UpdateDto.Name" type="text" class="form-control" value="@Model.Line.Name">
                    </div>
                </div>
                <div class="modal-footer">
                    @*<a class="btn btn-primary" href="#0">Save</a>*@
                    <button type="submit" class="btn_1 medium">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>

BusTracking.Web/Areas/Admin/Views/Line/Index.cshtml
@model LineCompositeViewModel;
@{
    ViewData["Title"] = "Lines Page";
}

@section Css{

}
@section Scripts{
    <script src="~/AdminSection/js/admin-datatables.js"></script>
}


<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Lines</li>
    </ol>
    <!-- Example DataTables Card-->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Lines Table
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Company</th>
                            <th>Bus</th>
                            <th>Status</th>
                            <th>Expired</th>
                            @if (@ViewBag.UserType == UserType.CompanyAdmin.ToString())
                            {
                                <th>Oprations</th>
                            }
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Company</th>
                            <th>Bus</th>
                            <th>Status</th>
                            <th>Expired</th>
                            @if (@ViewBag.UserType == UserType.CompanyAdmin.ToString())
                            {
                                <th>Oprations</th>
                            }
                        </tr>
                    </tfoot>
                    <tbody>

                        @if (Model.ListLines.Any())
                        {
                            foreach (var line in Model.ListLines)
                            {
                                <tr>
                                    <td>@line.Id</td>
                                    <td><a href="~/Admin/Line/Details/@line.Id">@line.Name</a></td>
                                    <td>@line.Company.Name</td>
                                    @*<td>@line.Bus.Name</td>*@
                                    <td>
                                        @if (line.Bus != null)
                                        {
                                            <a href="~/Admin/Bus/Details/@line.Bus.Id">@line.Bus.Name</a>
                                        }
                                        else
                                        {
                                            <a>Null</a>
                                        }
                                    </td>
                                    <td>
                                        <i class="@(line.Bus != null ? "approved" : "cancel")">
                                            @(line.Bus != null ? "Active" : "Inactive")
                                        </i>
                                    </td>
                                    <td>
                                        <i class="@(@line.ActiveExpired > DateTime.Now ? "approved" : "cancel")">
                                            @line.ActiveExpired
                                        </i>
                                    </td>
                                    @if (@ViewBag.UserType == UserType.CompanyAdmin.ToString())
                                    {
                                        <td>
                                            @*  <a href="edit-order.html"><strong>Edit</strong></a> |  <a href="#0"><strong>Delete</strong></a>*@
                                            <a href="~/Admin/Line/Delete/@line.Id" onclick="return confirm('Are you sure you want to delete ?');"><strong>Delete</strong></a>

                                        </td>
                                    }
                                </tr>
                            }
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /tables-->
</div>

<!-- Create New Line Modal -->
<form action="~/Admin/Line/Create" method="post" enctype="multipart/form-data">
    <div class="modal fade" id="client_detail_modal" tabindex="-1" role="dialog" aria-labelledby="client_detail_modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="client_detail_modalLabel">Edit company detail</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input required asp-for="CreateDto.Name" type="text" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    @*<a class="btn btn-primary" href="#0">Save</a>*@
                    <button type="submit" class="btn_1 medium">Save</button>
                </div>
            </div>

        </div>
    </div>
</form>